version: "3.9"

networks:
  dockerapi-dev:
    driver: bridge

services:
  programengineering:
    environment:
      - DB_CONNECTION_STRING=server=postgres_image;port=5432;database=picturedb;username=pictureuser;password=pictureuser
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    build:
      context: .
      dockerfile: ProgramEngineering/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - dockerapi-dev

  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.crt:/etc/nginx/cert.crt
      - ./cert.rsa:/etc/nginx/cert.rsa
    depends_on:
      - programengineering
    ports:
      - "4001:4001"
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "pictureuser"
      POSTGRES_PASSWORD: "pictureuser"
      POSTGRES_DB: "picturedb"
    networks:
      - dockerapi-dev
